/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.unodsl.ui.internal.UnodslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UnoDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(UnodslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		UnodslActivator activator = UnodslActivator.getInstance();
		return activator != null ? activator.getInjector(UnodslActivator.ORG_XTEXT_EXAMPLE_MYDSL_UNODSL) : null;
	}

}
