/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.unoDsl.CartesSpeciales;
import org.xtext.example.mydsl.unoDsl.EnumCartes;
import org.xtext.example.mydsl.unoDsl.UnoDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cartes Speciales</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.CartesSpecialesImpl#getEnumCartes <em>Enum Cartes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CartesSpecialesImpl extends MinimalEObjectImpl.Container implements CartesSpeciales
{
  /**
   * The cached value of the '{@link #getEnumCartes() <em>Enum Cartes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumCartes()
   * @generated
   * @ordered
   */
  protected EList<EnumCartes> enumCartes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CartesSpecialesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnoDslPackage.Literals.CARTES_SPECIALES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EnumCartes> getEnumCartes()
  {
    if (enumCartes == null)
    {
      enumCartes = new EObjectContainmentEList<EnumCartes>(EnumCartes.class, this, UnoDslPackage.CARTES_SPECIALES__ENUM_CARTES);
    }
    return enumCartes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UnoDslPackage.CARTES_SPECIALES__ENUM_CARTES:
        return ((InternalEList<?>)getEnumCartes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnoDslPackage.CARTES_SPECIALES__ENUM_CARTES:
        return getEnumCartes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnoDslPackage.CARTES_SPECIALES__ENUM_CARTES:
        getEnumCartes().clear();
        getEnumCartes().addAll((Collection<? extends EnumCartes>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnoDslPackage.CARTES_SPECIALES__ENUM_CARTES:
        getEnumCartes().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnoDslPackage.CARTES_SPECIALES__ENUM_CARTES:
        return enumCartes != null && !enumCartes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //CartesSpecialesImpl
