/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.unoDsl.DeposeCartes;
import org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes;
import org.xtext.example.mydsl.unoDsl.UnoDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Depose Cartes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.DeposeCartesImpl#getEnumReglesDeposeCartes <em>Enum Regles Depose Cartes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeposeCartesImpl extends MinimalEObjectImpl.Container implements DeposeCartes
{
  /**
   * The cached value of the '{@link #getEnumReglesDeposeCartes() <em>Enum Regles Depose Cartes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumReglesDeposeCartes()
   * @generated
   * @ordered
   */
  protected EList<EnumReglesDeposeCartes> enumReglesDeposeCartes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeposeCartesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnoDslPackage.Literals.DEPOSE_CARTES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EnumReglesDeposeCartes> getEnumReglesDeposeCartes()
  {
    if (enumReglesDeposeCartes == null)
    {
      enumReglesDeposeCartes = new EObjectContainmentEList<EnumReglesDeposeCartes>(EnumReglesDeposeCartes.class, this, UnoDslPackage.DEPOSE_CARTES__ENUM_REGLES_DEPOSE_CARTES);
    }
    return enumReglesDeposeCartes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UnoDslPackage.DEPOSE_CARTES__ENUM_REGLES_DEPOSE_CARTES:
        return ((InternalEList<?>)getEnumReglesDeposeCartes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnoDslPackage.DEPOSE_CARTES__ENUM_REGLES_DEPOSE_CARTES:
        return getEnumReglesDeposeCartes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnoDslPackage.DEPOSE_CARTES__ENUM_REGLES_DEPOSE_CARTES:
        getEnumReglesDeposeCartes().clear();
        getEnumReglesDeposeCartes().addAll((Collection<? extends EnumReglesDeposeCartes>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnoDslPackage.DEPOSE_CARTES__ENUM_REGLES_DEPOSE_CARTES:
        getEnumReglesDeposeCartes().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnoDslPackage.DEPOSE_CARTES__ENUM_REGLES_DEPOSE_CARTES:
        return enumReglesDeposeCartes != null && !enumReglesDeposeCartes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DeposeCartesImpl
