/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes;
import org.xtext.example.mydsl.unoDsl.UnoDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enum Regles Depose Cartes</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.EnumReglesDeposeCartesImpl#getCumulPlusDeux <em>Cumul Plus Deux</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.EnumReglesDeposeCartesImpl#getCumulPlusQuatre <em>Cumul Plus Quatre</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.EnumReglesDeposeCartesImpl#getSuiteClassique <em>Suite Classique</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.EnumReglesDeposeCartesImpl#getSuiteRoyale <em>Suite Royale</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.EnumReglesDeposeCartesImpl#getInterception <em>Interception</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.EnumReglesDeposeCartesImpl#getPlus4OuRien <em>Plus4 Ou Rien</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnumReglesDeposeCartesImpl extends MinimalEObjectImpl.Container implements EnumReglesDeposeCartes
{
  /**
   * The default value of the '{@link #getCumulPlusDeux() <em>Cumul Plus Deux</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumulPlusDeux()
   * @generated
   * @ordered
   */
  protected static final String CUMUL_PLUS_DEUX_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCumulPlusDeux() <em>Cumul Plus Deux</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumulPlusDeux()
   * @generated
   * @ordered
   */
  protected String cumulPlusDeux = CUMUL_PLUS_DEUX_EDEFAULT;

  /**
   * The default value of the '{@link #getCumulPlusQuatre() <em>Cumul Plus Quatre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumulPlusQuatre()
   * @generated
   * @ordered
   */
  protected static final String CUMUL_PLUS_QUATRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCumulPlusQuatre() <em>Cumul Plus Quatre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumulPlusQuatre()
   * @generated
   * @ordered
   */
  protected String cumulPlusQuatre = CUMUL_PLUS_QUATRE_EDEFAULT;

  /**
   * The default value of the '{@link #getSuiteClassique() <em>Suite Classique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuiteClassique()
   * @generated
   * @ordered
   */
  protected static final String SUITE_CLASSIQUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSuiteClassique() <em>Suite Classique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuiteClassique()
   * @generated
   * @ordered
   */
  protected String suiteClassique = SUITE_CLASSIQUE_EDEFAULT;

  /**
   * The default value of the '{@link #getSuiteRoyale() <em>Suite Royale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuiteRoyale()
   * @generated
   * @ordered
   */
  protected static final String SUITE_ROYALE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSuiteRoyale() <em>Suite Royale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuiteRoyale()
   * @generated
   * @ordered
   */
  protected String suiteRoyale = SUITE_ROYALE_EDEFAULT;

  /**
   * The default value of the '{@link #getInterception() <em>Interception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInterception()
   * @generated
   * @ordered
   */
  protected static final String INTERCEPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInterception() <em>Interception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInterception()
   * @generated
   * @ordered
   */
  protected String interception = INTERCEPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getPlus4OuRien() <em>Plus4 Ou Rien</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlus4OuRien()
   * @generated
   * @ordered
   */
  protected static final String PLUS4_OU_RIEN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPlus4OuRien() <em>Plus4 Ou Rien</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlus4OuRien()
   * @generated
   * @ordered
   */
  protected String plus4OuRien = PLUS4_OU_RIEN_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnumReglesDeposeCartesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnoDslPackage.Literals.ENUM_REGLES_DEPOSE_CARTES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCumulPlusDeux()
  {
    return cumulPlusDeux;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCumulPlusDeux(String newCumulPlusDeux)
  {
    String oldCumulPlusDeux = cumulPlusDeux;
    cumulPlusDeux = newCumulPlusDeux;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_DEUX, oldCumulPlusDeux, cumulPlusDeux));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCumulPlusQuatre()
  {
    return cumulPlusQuatre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCumulPlusQuatre(String newCumulPlusQuatre)
  {
    String oldCumulPlusQuatre = cumulPlusQuatre;
    cumulPlusQuatre = newCumulPlusQuatre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_QUATRE, oldCumulPlusQuatre, cumulPlusQuatre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSuiteClassique()
  {
    return suiteClassique;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuiteClassique(String newSuiteClassique)
  {
    String oldSuiteClassique = suiteClassique;
    suiteClassique = newSuiteClassique;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__SUITE_CLASSIQUE, oldSuiteClassique, suiteClassique));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSuiteRoyale()
  {
    return suiteRoyale;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuiteRoyale(String newSuiteRoyale)
  {
    String oldSuiteRoyale = suiteRoyale;
    suiteRoyale = newSuiteRoyale;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__SUITE_ROYALE, oldSuiteRoyale, suiteRoyale));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInterception()
  {
    return interception;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInterception(String newInterception)
  {
    String oldInterception = interception;
    interception = newInterception;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__INTERCEPTION, oldInterception, interception));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPlus4OuRien()
  {
    return plus4OuRien;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPlus4OuRien(String newPlus4OuRien)
  {
    String oldPlus4OuRien = plus4OuRien;
    plus4OuRien = newPlus4OuRien;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__PLUS4_OU_RIEN, oldPlus4OuRien, plus4OuRien));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_DEUX:
        return getCumulPlusDeux();
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_QUATRE:
        return getCumulPlusQuatre();
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__SUITE_CLASSIQUE:
        return getSuiteClassique();
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__SUITE_ROYALE:
        return getSuiteRoyale();
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__INTERCEPTION:
        return getInterception();
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__PLUS4_OU_RIEN:
        return getPlus4OuRien();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_DEUX:
        setCumulPlusDeux((String)newValue);
        return;
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_QUATRE:
        setCumulPlusQuatre((String)newValue);
        return;
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__SUITE_CLASSIQUE:
        setSuiteClassique((String)newValue);
        return;
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__SUITE_ROYALE:
        setSuiteRoyale((String)newValue);
        return;
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__INTERCEPTION:
        setInterception((String)newValue);
        return;
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__PLUS4_OU_RIEN:
        setPlus4OuRien((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_DEUX:
        setCumulPlusDeux(CUMUL_PLUS_DEUX_EDEFAULT);
        return;
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_QUATRE:
        setCumulPlusQuatre(CUMUL_PLUS_QUATRE_EDEFAULT);
        return;
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__SUITE_CLASSIQUE:
        setSuiteClassique(SUITE_CLASSIQUE_EDEFAULT);
        return;
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__SUITE_ROYALE:
        setSuiteRoyale(SUITE_ROYALE_EDEFAULT);
        return;
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__INTERCEPTION:
        setInterception(INTERCEPTION_EDEFAULT);
        return;
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__PLUS4_OU_RIEN:
        setPlus4OuRien(PLUS4_OU_RIEN_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_DEUX:
        return CUMUL_PLUS_DEUX_EDEFAULT == null ? cumulPlusDeux != null : !CUMUL_PLUS_DEUX_EDEFAULT.equals(cumulPlusDeux);
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_QUATRE:
        return CUMUL_PLUS_QUATRE_EDEFAULT == null ? cumulPlusQuatre != null : !CUMUL_PLUS_QUATRE_EDEFAULT.equals(cumulPlusQuatre);
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__SUITE_CLASSIQUE:
        return SUITE_CLASSIQUE_EDEFAULT == null ? suiteClassique != null : !SUITE_CLASSIQUE_EDEFAULT.equals(suiteClassique);
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__SUITE_ROYALE:
        return SUITE_ROYALE_EDEFAULT == null ? suiteRoyale != null : !SUITE_ROYALE_EDEFAULT.equals(suiteRoyale);
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__INTERCEPTION:
        return INTERCEPTION_EDEFAULT == null ? interception != null : !INTERCEPTION_EDEFAULT.equals(interception);
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES__PLUS4_OU_RIEN:
        return PLUS4_OU_RIEN_EDEFAULT == null ? plus4OuRien != null : !PLUS4_OU_RIEN_EDEFAULT.equals(plus4OuRien);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (cumulPlusDeux: ");
    result.append(cumulPlusDeux);
    result.append(", cumulPlusQuatre: ");
    result.append(cumulPlusQuatre);
    result.append(", suiteClassique: ");
    result.append(suiteClassique);
    result.append(", suiteRoyale: ");
    result.append(suiteRoyale);
    result.append(", interception: ");
    result.append(interception);
    result.append(", plus4OuRien: ");
    result.append(plus4OuRien);
    result.append(')');
    return result.toString();
  }

} //EnumReglesDeposeCartesImpl
