/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.unoDsl.CartesSpeciales;
import org.xtext.example.mydsl.unoDsl.DeposeCartes;
import org.xtext.example.mydsl.unoDsl.NbCartesTalon;
import org.xtext.example.mydsl.unoDsl.NombreDePioches;
import org.xtext.example.mydsl.unoDsl.UnoConfig;
import org.xtext.example.mydsl.unoDsl.UnoDslPackage;
import org.xtext.example.mydsl.unoDsl.Visibilite;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Uno Config</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl#getNbCartesTalon <em>Nb Cartes Talon</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl#getTempsLimite <em>Temps Limite</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl#getDeposeCartes <em>Depose Cartes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl#getNombreDePiles <em>Nombre De Piles</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl#getCartesSpeciales <em>Cartes Speciales</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl#getNombreDePioches <em>Nombre De Pioches</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UnoConfigImpl extends MinimalEObjectImpl.Container implements UnoConfig
{
  /**
   * The default value of the '{@link #getNbCartesTalon() <em>Nb Cartes Talon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbCartesTalon()
   * @generated
   * @ordered
   */
  protected static final NbCartesTalon NB_CARTES_TALON_EDEFAULT = NbCartesTalon.UNE_CARTE_TALON;

  /**
   * The cached value of the '{@link #getNbCartesTalon() <em>Nb Cartes Talon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNbCartesTalon()
   * @generated
   * @ordered
   */
  protected NbCartesTalon nbCartesTalon = NB_CARTES_TALON_EDEFAULT;

  /**
   * The default value of the '{@link #getTempsLimite() <em>Temps Limite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTempsLimite()
   * @generated
   * @ordered
   */
  protected static final String TEMPS_LIMITE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTempsLimite() <em>Temps Limite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTempsLimite()
   * @generated
   * @ordered
   */
  protected String tempsLimite = TEMPS_LIMITE_EDEFAULT;

  /**
   * The cached value of the '{@link #getDeposeCartes() <em>Depose Cartes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeposeCartes()
   * @generated
   * @ordered
   */
  protected DeposeCartes deposeCartes;

  /**
   * The cached value of the '{@link #getVisibilite() <em>Visibilite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibilite()
   * @generated
   * @ordered
   */
  protected Visibilite visibilite;

  /**
   * The default value of the '{@link #getNombreDePiles() <em>Nombre De Piles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombreDePiles()
   * @generated
   * @ordered
   */
  protected static final String NOMBRE_DE_PILES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNombreDePiles() <em>Nombre De Piles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombreDePiles()
   * @generated
   * @ordered
   */
  protected String nombreDePiles = NOMBRE_DE_PILES_EDEFAULT;

  /**
   * The cached value of the '{@link #getCartesSpeciales() <em>Cartes Speciales</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCartesSpeciales()
   * @generated
   * @ordered
   */
  protected CartesSpeciales cartesSpeciales;

  /**
   * The cached value of the '{@link #getNombreDePioches() <em>Nombre De Pioches</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombreDePioches()
   * @generated
   * @ordered
   */
  protected NombreDePioches nombreDePioches;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UnoConfigImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnoDslPackage.Literals.UNO_CONFIG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NbCartesTalon getNbCartesTalon()
  {
    return nbCartesTalon;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNbCartesTalon(NbCartesTalon newNbCartesTalon)
  {
    NbCartesTalon oldNbCartesTalon = nbCartesTalon;
    nbCartesTalon = newNbCartesTalon == null ? NB_CARTES_TALON_EDEFAULT : newNbCartesTalon;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__NB_CARTES_TALON, oldNbCartesTalon, nbCartesTalon));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTempsLimite()
  {
    return tempsLimite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTempsLimite(String newTempsLimite)
  {
    String oldTempsLimite = tempsLimite;
    tempsLimite = newTempsLimite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__TEMPS_LIMITE, oldTempsLimite, tempsLimite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeposeCartes getDeposeCartes()
  {
    return deposeCartes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDeposeCartes(DeposeCartes newDeposeCartes, NotificationChain msgs)
  {
    DeposeCartes oldDeposeCartes = deposeCartes;
    deposeCartes = newDeposeCartes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__DEPOSE_CARTES, oldDeposeCartes, newDeposeCartes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeposeCartes(DeposeCartes newDeposeCartes)
  {
    if (newDeposeCartes != deposeCartes)
    {
      NotificationChain msgs = null;
      if (deposeCartes != null)
        msgs = ((InternalEObject)deposeCartes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UnoDslPackage.UNO_CONFIG__DEPOSE_CARTES, null, msgs);
      if (newDeposeCartes != null)
        msgs = ((InternalEObject)newDeposeCartes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UnoDslPackage.UNO_CONFIG__DEPOSE_CARTES, null, msgs);
      msgs = basicSetDeposeCartes(newDeposeCartes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__DEPOSE_CARTES, newDeposeCartes, newDeposeCartes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Visibilite getVisibilite()
  {
    return visibilite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVisibilite(Visibilite newVisibilite, NotificationChain msgs)
  {
    Visibilite oldVisibilite = visibilite;
    visibilite = newVisibilite;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__VISIBILITE, oldVisibilite, newVisibilite);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibilite(Visibilite newVisibilite)
  {
    if (newVisibilite != visibilite)
    {
      NotificationChain msgs = null;
      if (visibilite != null)
        msgs = ((InternalEObject)visibilite).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UnoDslPackage.UNO_CONFIG__VISIBILITE, null, msgs);
      if (newVisibilite != null)
        msgs = ((InternalEObject)newVisibilite).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UnoDslPackage.UNO_CONFIG__VISIBILITE, null, msgs);
      msgs = basicSetVisibilite(newVisibilite, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__VISIBILITE, newVisibilite, newVisibilite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNombreDePiles()
  {
    return nombreDePiles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNombreDePiles(String newNombreDePiles)
  {
    String oldNombreDePiles = nombreDePiles;
    nombreDePiles = newNombreDePiles;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PILES, oldNombreDePiles, nombreDePiles));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CartesSpeciales getCartesSpeciales()
  {
    return cartesSpeciales;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCartesSpeciales(CartesSpeciales newCartesSpeciales, NotificationChain msgs)
  {
    CartesSpeciales oldCartesSpeciales = cartesSpeciales;
    cartesSpeciales = newCartesSpeciales;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__CARTES_SPECIALES, oldCartesSpeciales, newCartesSpeciales);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCartesSpeciales(CartesSpeciales newCartesSpeciales)
  {
    if (newCartesSpeciales != cartesSpeciales)
    {
      NotificationChain msgs = null;
      if (cartesSpeciales != null)
        msgs = ((InternalEObject)cartesSpeciales).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UnoDslPackage.UNO_CONFIG__CARTES_SPECIALES, null, msgs);
      if (newCartesSpeciales != null)
        msgs = ((InternalEObject)newCartesSpeciales).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UnoDslPackage.UNO_CONFIG__CARTES_SPECIALES, null, msgs);
      msgs = basicSetCartesSpeciales(newCartesSpeciales, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__CARTES_SPECIALES, newCartesSpeciales, newCartesSpeciales));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NombreDePioches getNombreDePioches()
  {
    return nombreDePioches;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNombreDePioches(NombreDePioches newNombreDePioches, NotificationChain msgs)
  {
    NombreDePioches oldNombreDePioches = nombreDePioches;
    nombreDePioches = newNombreDePioches;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PIOCHES, oldNombreDePioches, newNombreDePioches);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNombreDePioches(NombreDePioches newNombreDePioches)
  {
    if (newNombreDePioches != nombreDePioches)
    {
      NotificationChain msgs = null;
      if (nombreDePioches != null)
        msgs = ((InternalEObject)nombreDePioches).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PIOCHES, null, msgs);
      if (newNombreDePioches != null)
        msgs = ((InternalEObject)newNombreDePioches).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PIOCHES, null, msgs);
      msgs = basicSetNombreDePioches(newNombreDePioches, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PIOCHES, newNombreDePioches, newNombreDePioches));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case UnoDslPackage.UNO_CONFIG__DEPOSE_CARTES:
        return basicSetDeposeCartes(null, msgs);
      case UnoDslPackage.UNO_CONFIG__VISIBILITE:
        return basicSetVisibilite(null, msgs);
      case UnoDslPackage.UNO_CONFIG__CARTES_SPECIALES:
        return basicSetCartesSpeciales(null, msgs);
      case UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PIOCHES:
        return basicSetNombreDePioches(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnoDslPackage.UNO_CONFIG__NB_CARTES_TALON:
        return getNbCartesTalon();
      case UnoDslPackage.UNO_CONFIG__TEMPS_LIMITE:
        return getTempsLimite();
      case UnoDslPackage.UNO_CONFIG__DEPOSE_CARTES:
        return getDeposeCartes();
      case UnoDslPackage.UNO_CONFIG__VISIBILITE:
        return getVisibilite();
      case UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PILES:
        return getNombreDePiles();
      case UnoDslPackage.UNO_CONFIG__CARTES_SPECIALES:
        return getCartesSpeciales();
      case UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PIOCHES:
        return getNombreDePioches();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnoDslPackage.UNO_CONFIG__NB_CARTES_TALON:
        setNbCartesTalon((NbCartesTalon)newValue);
        return;
      case UnoDslPackage.UNO_CONFIG__TEMPS_LIMITE:
        setTempsLimite((String)newValue);
        return;
      case UnoDslPackage.UNO_CONFIG__DEPOSE_CARTES:
        setDeposeCartes((DeposeCartes)newValue);
        return;
      case UnoDslPackage.UNO_CONFIG__VISIBILITE:
        setVisibilite((Visibilite)newValue);
        return;
      case UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PILES:
        setNombreDePiles((String)newValue);
        return;
      case UnoDslPackage.UNO_CONFIG__CARTES_SPECIALES:
        setCartesSpeciales((CartesSpeciales)newValue);
        return;
      case UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PIOCHES:
        setNombreDePioches((NombreDePioches)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnoDslPackage.UNO_CONFIG__NB_CARTES_TALON:
        setNbCartesTalon(NB_CARTES_TALON_EDEFAULT);
        return;
      case UnoDslPackage.UNO_CONFIG__TEMPS_LIMITE:
        setTempsLimite(TEMPS_LIMITE_EDEFAULT);
        return;
      case UnoDslPackage.UNO_CONFIG__DEPOSE_CARTES:
        setDeposeCartes((DeposeCartes)null);
        return;
      case UnoDslPackage.UNO_CONFIG__VISIBILITE:
        setVisibilite((Visibilite)null);
        return;
      case UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PILES:
        setNombreDePiles(NOMBRE_DE_PILES_EDEFAULT);
        return;
      case UnoDslPackage.UNO_CONFIG__CARTES_SPECIALES:
        setCartesSpeciales((CartesSpeciales)null);
        return;
      case UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PIOCHES:
        setNombreDePioches((NombreDePioches)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnoDslPackage.UNO_CONFIG__NB_CARTES_TALON:
        return nbCartesTalon != NB_CARTES_TALON_EDEFAULT;
      case UnoDslPackage.UNO_CONFIG__TEMPS_LIMITE:
        return TEMPS_LIMITE_EDEFAULT == null ? tempsLimite != null : !TEMPS_LIMITE_EDEFAULT.equals(tempsLimite);
      case UnoDslPackage.UNO_CONFIG__DEPOSE_CARTES:
        return deposeCartes != null;
      case UnoDslPackage.UNO_CONFIG__VISIBILITE:
        return visibilite != null;
      case UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PILES:
        return NOMBRE_DE_PILES_EDEFAULT == null ? nombreDePiles != null : !NOMBRE_DE_PILES_EDEFAULT.equals(nombreDePiles);
      case UnoDslPackage.UNO_CONFIG__CARTES_SPECIALES:
        return cartesSpeciales != null;
      case UnoDslPackage.UNO_CONFIG__NOMBRE_DE_PIOCHES:
        return nombreDePioches != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nbCartesTalon: ");
    result.append(nbCartesTalon);
    result.append(", tempsLimite: ");
    result.append(tempsLimite);
    result.append(", nombreDePiles: ");
    result.append(nombreDePiles);
    result.append(')');
    return result.toString();
  }

} //UnoConfigImpl
