/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl.unoDsl.CartesSpeciales;
import org.xtext.example.mydsl.unoDsl.DeposeCartes;
import org.xtext.example.mydsl.unoDsl.EnumCartes;
import org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes;
import org.xtext.example.mydsl.unoDsl.Model;
import org.xtext.example.mydsl.unoDsl.NbCartesTalon;
import org.xtext.example.mydsl.unoDsl.NombreDePioches;
import org.xtext.example.mydsl.unoDsl.PeutJouer;
import org.xtext.example.mydsl.unoDsl.UnoConfig;
import org.xtext.example.mydsl.unoDsl.UnoDslFactory;
import org.xtext.example.mydsl.unoDsl.UnoDslPackage;
import org.xtext.example.mydsl.unoDsl.Visibilite;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class UnoDslPackageImpl extends EPackageImpl implements UnoDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass unoConfigEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass deposeCartesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass enumReglesDeposeCartesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass visibiliteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cartesSpecialesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass enumCartesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nombreDePiochesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass peutJouerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum nbCartesTalonEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private UnoDslPackageImpl()
  {
    super(eNS_URI, UnoDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link UnoDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static UnoDslPackage init()
  {
    if (isInited) return (UnoDslPackage)EPackage.Registry.INSTANCE.getEPackage(UnoDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredUnoDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    UnoDslPackageImpl theUnoDslPackage = registeredUnoDslPackage instanceof UnoDslPackageImpl ? (UnoDslPackageImpl)registeredUnoDslPackage : new UnoDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theUnoDslPackage.createPackageContents();

    // Initialize created meta-data
    theUnoDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theUnoDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(UnoDslPackage.eNS_URI, theUnoDslPackage);
    return theUnoDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_UnoRules()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUnoConfig()
  {
    return unoConfigEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoConfig_NbCartesTalon()
  {
    return (EAttribute)unoConfigEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoConfig_TempsLimite()
  {
    return (EAttribute)unoConfigEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUnoConfig_DeposeCartes()
  {
    return (EReference)unoConfigEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUnoConfig_Visibilite()
  {
    return (EReference)unoConfigEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoConfig_NombreDePiles()
  {
    return (EAttribute)unoConfigEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUnoConfig_CartesSpeciales()
  {
    return (EReference)unoConfigEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUnoConfig_NombreDePioches()
  {
    return (EReference)unoConfigEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeposeCartes()
  {
    return deposeCartesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeposeCartes_EnumReglesDeposeCartes()
  {
    return (EReference)deposeCartesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEnumReglesDeposeCartes()
  {
    return enumReglesDeposeCartesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumReglesDeposeCartes_CumulPlusDeux()
  {
    return (EAttribute)enumReglesDeposeCartesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumReglesDeposeCartes_CumulPlusQuatre()
  {
    return (EAttribute)enumReglesDeposeCartesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumReglesDeposeCartes_SuiteClassique()
  {
    return (EAttribute)enumReglesDeposeCartesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumReglesDeposeCartes_SuiteRoyale()
  {
    return (EAttribute)enumReglesDeposeCartesEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumReglesDeposeCartes_Interception()
  {
    return (EAttribute)enumReglesDeposeCartesEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumReglesDeposeCartes_Plus4OuRien()
  {
    return (EAttribute)enumReglesDeposeCartesEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVisibilite()
  {
    return visibiliteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVisibilite_Visible()
  {
    return (EAttribute)visibiliteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVisibilite_Invisible()
  {
    return (EAttribute)visibiliteEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCartesSpeciales()
  {
    return cartesSpecialesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCartesSpeciales_EnumCartes()
  {
    return (EReference)cartesSpecialesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEnumCartes()
  {
    return enumCartesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumCartes_CarteUno()
  {
    return (EAttribute)enumCartesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumCartes_PlusQuatreNonContestable()
  {
    return (EAttribute)enumCartesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumCartes_CarteZero()
  {
    return (EAttribute)enumCartesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEnumCartes_CarteSept()
  {
    return (EAttribute)enumCartesEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNombreDePioches()
  {
    return nombreDePiochesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNombreDePioches_UneFois()
  {
    return (EAttribute)nombreDePiochesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNombreDePioches_PeutJouer()
  {
    return (EReference)nombreDePiochesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNombreDePioches_TroisFois()
  {
    return (EAttribute)nombreDePiochesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPeutJouer()
  {
    return peutJouerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPeutJouer_PeutJouerEnsuite()
  {
    return (EAttribute)peutJouerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPeutJouer_PeutPasJouerEnsuite()
  {
    return (EAttribute)peutJouerEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getNbCartesTalon()
  {
    return nbCartesTalonEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UnoDslFactory getUnoDslFactory()
  {
    return (UnoDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__UNO_RULES);

    unoConfigEClass = createEClass(UNO_CONFIG);
    createEAttribute(unoConfigEClass, UNO_CONFIG__NB_CARTES_TALON);
    createEAttribute(unoConfigEClass, UNO_CONFIG__TEMPS_LIMITE);
    createEReference(unoConfigEClass, UNO_CONFIG__DEPOSE_CARTES);
    createEReference(unoConfigEClass, UNO_CONFIG__VISIBILITE);
    createEAttribute(unoConfigEClass, UNO_CONFIG__NOMBRE_DE_PILES);
    createEReference(unoConfigEClass, UNO_CONFIG__CARTES_SPECIALES);
    createEReference(unoConfigEClass, UNO_CONFIG__NOMBRE_DE_PIOCHES);

    deposeCartesEClass = createEClass(DEPOSE_CARTES);
    createEReference(deposeCartesEClass, DEPOSE_CARTES__ENUM_REGLES_DEPOSE_CARTES);

    enumReglesDeposeCartesEClass = createEClass(ENUM_REGLES_DEPOSE_CARTES);
    createEAttribute(enumReglesDeposeCartesEClass, ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_DEUX);
    createEAttribute(enumReglesDeposeCartesEClass, ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_QUATRE);
    createEAttribute(enumReglesDeposeCartesEClass, ENUM_REGLES_DEPOSE_CARTES__SUITE_CLASSIQUE);
    createEAttribute(enumReglesDeposeCartesEClass, ENUM_REGLES_DEPOSE_CARTES__SUITE_ROYALE);
    createEAttribute(enumReglesDeposeCartesEClass, ENUM_REGLES_DEPOSE_CARTES__INTERCEPTION);
    createEAttribute(enumReglesDeposeCartesEClass, ENUM_REGLES_DEPOSE_CARTES__PLUS4_OU_RIEN);

    visibiliteEClass = createEClass(VISIBILITE);
    createEAttribute(visibiliteEClass, VISIBILITE__VISIBLE);
    createEAttribute(visibiliteEClass, VISIBILITE__INVISIBLE);

    cartesSpecialesEClass = createEClass(CARTES_SPECIALES);
    createEReference(cartesSpecialesEClass, CARTES_SPECIALES__ENUM_CARTES);

    enumCartesEClass = createEClass(ENUM_CARTES);
    createEAttribute(enumCartesEClass, ENUM_CARTES__CARTE_UNO);
    createEAttribute(enumCartesEClass, ENUM_CARTES__PLUS_QUATRE_NON_CONTESTABLE);
    createEAttribute(enumCartesEClass, ENUM_CARTES__CARTE_ZERO);
    createEAttribute(enumCartesEClass, ENUM_CARTES__CARTE_SEPT);

    nombreDePiochesEClass = createEClass(NOMBRE_DE_PIOCHES);
    createEAttribute(nombreDePiochesEClass, NOMBRE_DE_PIOCHES__UNE_FOIS);
    createEReference(nombreDePiochesEClass, NOMBRE_DE_PIOCHES__PEUT_JOUER);
    createEAttribute(nombreDePiochesEClass, NOMBRE_DE_PIOCHES__TROIS_FOIS);

    peutJouerEClass = createEClass(PEUT_JOUER);
    createEAttribute(peutJouerEClass, PEUT_JOUER__PEUT_JOUER_ENSUITE);
    createEAttribute(peutJouerEClass, PEUT_JOUER__PEUT_PAS_JOUER_ENSUITE);

    // Create enums
    nbCartesTalonEEnum = createEEnum(NB_CARTES_TALON);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_UnoRules(), this.getUnoConfig(), null, "unoRules", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(unoConfigEClass, UnoConfig.class, "UnoConfig", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUnoConfig_NbCartesTalon(), this.getNbCartesTalon(), "nbCartesTalon", null, 0, 1, UnoConfig.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoConfig_TempsLimite(), ecorePackage.getEString(), "tempsLimite", null, 0, 1, UnoConfig.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUnoConfig_DeposeCartes(), this.getDeposeCartes(), null, "deposeCartes", null, 0, 1, UnoConfig.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUnoConfig_Visibilite(), this.getVisibilite(), null, "visibilite", null, 0, 1, UnoConfig.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoConfig_NombreDePiles(), ecorePackage.getEString(), "nombreDePiles", null, 0, 1, UnoConfig.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUnoConfig_CartesSpeciales(), this.getCartesSpeciales(), null, "cartesSpeciales", null, 0, 1, UnoConfig.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUnoConfig_NombreDePioches(), this.getNombreDePioches(), null, "nombreDePioches", null, 0, 1, UnoConfig.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(deposeCartesEClass, DeposeCartes.class, "DeposeCartes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeposeCartes_EnumReglesDeposeCartes(), this.getEnumReglesDeposeCartes(), null, "enumReglesDeposeCartes", null, 0, -1, DeposeCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(enumReglesDeposeCartesEClass, EnumReglesDeposeCartes.class, "EnumReglesDeposeCartes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEnumReglesDeposeCartes_CumulPlusDeux(), ecorePackage.getEString(), "cumulPlusDeux", null, 0, 1, EnumReglesDeposeCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnumReglesDeposeCartes_CumulPlusQuatre(), ecorePackage.getEString(), "cumulPlusQuatre", null, 0, 1, EnumReglesDeposeCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnumReglesDeposeCartes_SuiteClassique(), ecorePackage.getEString(), "suiteClassique", null, 0, 1, EnumReglesDeposeCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnumReglesDeposeCartes_SuiteRoyale(), ecorePackage.getEString(), "suiteRoyale", null, 0, 1, EnumReglesDeposeCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnumReglesDeposeCartes_Interception(), ecorePackage.getEString(), "interception", null, 0, 1, EnumReglesDeposeCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnumReglesDeposeCartes_Plus4OuRien(), ecorePackage.getEString(), "plus4OuRien", null, 0, 1, EnumReglesDeposeCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(visibiliteEClass, Visibilite.class, "Visibilite", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVisibilite_Visible(), ecorePackage.getEString(), "visible", null, 0, 1, Visibilite.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVisibilite_Invisible(), ecorePackage.getEString(), "invisible", null, 0, 1, Visibilite.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(cartesSpecialesEClass, CartesSpeciales.class, "CartesSpeciales", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCartesSpeciales_EnumCartes(), this.getEnumCartes(), null, "enumCartes", null, 0, -1, CartesSpeciales.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(enumCartesEClass, EnumCartes.class, "EnumCartes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEnumCartes_CarteUno(), ecorePackage.getEString(), "carteUno", null, 0, 1, EnumCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnumCartes_PlusQuatreNonContestable(), ecorePackage.getEString(), "plusQuatreNonContestable", null, 0, 1, EnumCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnumCartes_CarteZero(), ecorePackage.getEString(), "carteZero", null, 0, 1, EnumCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnumCartes_CarteSept(), ecorePackage.getEString(), "carteSept", null, 0, 1, EnumCartes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(nombreDePiochesEClass, NombreDePioches.class, "NombreDePioches", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNombreDePioches_UneFois(), ecorePackage.getEString(), "uneFois", null, 0, 1, NombreDePioches.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNombreDePioches_PeutJouer(), this.getPeutJouer(), null, "peutJouer", null, 0, 1, NombreDePioches.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getNombreDePioches_TroisFois(), ecorePackage.getEString(), "troisFois", null, 0, 1, NombreDePioches.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(peutJouerEClass, PeutJouer.class, "PeutJouer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPeutJouer_PeutJouerEnsuite(), ecorePackage.getEString(), "peutJouerEnsuite", null, 0, 1, PeutJouer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPeutJouer_PeutPasJouerEnsuite(), ecorePackage.getEString(), "peutPasJouerEnsuite", null, 0, 1, PeutJouer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(nbCartesTalonEEnum, NbCartesTalon.class, "NbCartesTalon");
    addEEnumLiteral(nbCartesTalonEEnum, NbCartesTalon.UNE_CARTE_TALON);
    addEEnumLiteral(nbCartesTalonEEnum, NbCartesTalon.QUATRE_CARTES_TALON);

    // Create resource
    createResource(eNS_URI);
  }

} //UnoDslPackageImpl
