/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cartes Speciales</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.CartesSpeciales#getEnumCartes <em>Enum Cartes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getCartesSpeciales()
 * @model
 * @generated
 */
public interface CartesSpeciales extends EObject
{
  /**
   * Returns the value of the '<em><b>Enum Cartes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.unoDsl.EnumCartes}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Cartes</em>' containment reference list.
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getCartesSpeciales_EnumCartes()
   * @model containment="true"
   * @generated
   */
  EList<EnumCartes> getEnumCartes();

} // CartesSpeciales
