/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Depose Cartes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.DeposeCartes#getEnumReglesDeposeCartes <em>Enum Regles Depose Cartes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getDeposeCartes()
 * @model
 * @generated
 */
public interface DeposeCartes extends EObject
{
  /**
   * Returns the value of the '<em><b>Enum Regles Depose Cartes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Regles Depose Cartes</em>' containment reference list.
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getDeposeCartes_EnumReglesDeposeCartes()
   * @model containment="true"
   * @generated
   */
  EList<EnumReglesDeposeCartes> getEnumReglesDeposeCartes();

} // DeposeCartes
