/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Cartes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteUno <em>Carte Uno</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getPlusQuatreNonContestable <em>Plus Quatre Non Contestable</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteZero <em>Carte Zero</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteSept <em>Carte Sept</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumCartes()
 * @model
 * @generated
 */
public interface EnumCartes extends EObject
{
  /**
   * Returns the value of the '<em><b>Carte Uno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte Uno</em>' attribute.
   * @see #setCarteUno(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumCartes_CarteUno()
   * @model
   * @generated
   */
  String getCarteUno();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteUno <em>Carte Uno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Carte Uno</em>' attribute.
   * @see #getCarteUno()
   * @generated
   */
  void setCarteUno(String value);

  /**
   * Returns the value of the '<em><b>Plus Quatre Non Contestable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plus Quatre Non Contestable</em>' attribute.
   * @see #setPlusQuatreNonContestable(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumCartes_PlusQuatreNonContestable()
   * @model
   * @generated
   */
  String getPlusQuatreNonContestable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getPlusQuatreNonContestable <em>Plus Quatre Non Contestable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plus Quatre Non Contestable</em>' attribute.
   * @see #getPlusQuatreNonContestable()
   * @generated
   */
  void setPlusQuatreNonContestable(String value);

  /**
   * Returns the value of the '<em><b>Carte Zero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte Zero</em>' attribute.
   * @see #setCarteZero(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumCartes_CarteZero()
   * @model
   * @generated
   */
  String getCarteZero();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteZero <em>Carte Zero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Carte Zero</em>' attribute.
   * @see #getCarteZero()
   * @generated
   */
  void setCarteZero(String value);

  /**
   * Returns the value of the '<em><b>Carte Sept</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte Sept</em>' attribute.
   * @see #setCarteSept(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumCartes_CarteSept()
   * @model
   * @generated
   */
  String getCarteSept();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteSept <em>Carte Sept</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Carte Sept</em>' attribute.
   * @see #getCarteSept()
   * @generated
   */
  void setCarteSept(String value);

} // EnumCartes
