/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Regles Depose Cartes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getCumulPlusDeux <em>Cumul Plus Deux</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getCumulPlusQuatre <em>Cumul Plus Quatre</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getSuiteClassique <em>Suite Classique</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getSuiteRoyale <em>Suite Royale</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getInterception <em>Interception</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getPlus4OuRien <em>Plus4 Ou Rien</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumReglesDeposeCartes()
 * @model
 * @generated
 */
public interface EnumReglesDeposeCartes extends EObject
{
  /**
   * Returns the value of the '<em><b>Cumul Plus Deux</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cumul Plus Deux</em>' attribute.
   * @see #setCumulPlusDeux(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumReglesDeposeCartes_CumulPlusDeux()
   * @model
   * @generated
   */
  String getCumulPlusDeux();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getCumulPlusDeux <em>Cumul Plus Deux</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cumul Plus Deux</em>' attribute.
   * @see #getCumulPlusDeux()
   * @generated
   */
  void setCumulPlusDeux(String value);

  /**
   * Returns the value of the '<em><b>Cumul Plus Quatre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cumul Plus Quatre</em>' attribute.
   * @see #setCumulPlusQuatre(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumReglesDeposeCartes_CumulPlusQuatre()
   * @model
   * @generated
   */
  String getCumulPlusQuatre();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getCumulPlusQuatre <em>Cumul Plus Quatre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cumul Plus Quatre</em>' attribute.
   * @see #getCumulPlusQuatre()
   * @generated
   */
  void setCumulPlusQuatre(String value);

  /**
   * Returns the value of the '<em><b>Suite Classique</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Suite Classique</em>' attribute.
   * @see #setSuiteClassique(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumReglesDeposeCartes_SuiteClassique()
   * @model
   * @generated
   */
  String getSuiteClassique();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getSuiteClassique <em>Suite Classique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Suite Classique</em>' attribute.
   * @see #getSuiteClassique()
   * @generated
   */
  void setSuiteClassique(String value);

  /**
   * Returns the value of the '<em><b>Suite Royale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Suite Royale</em>' attribute.
   * @see #setSuiteRoyale(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumReglesDeposeCartes_SuiteRoyale()
   * @model
   * @generated
   */
  String getSuiteRoyale();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getSuiteRoyale <em>Suite Royale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Suite Royale</em>' attribute.
   * @see #getSuiteRoyale()
   * @generated
   */
  void setSuiteRoyale(String value);

  /**
   * Returns the value of the '<em><b>Interception</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interception</em>' attribute.
   * @see #setInterception(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumReglesDeposeCartes_Interception()
   * @model
   * @generated
   */
  String getInterception();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getInterception <em>Interception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interception</em>' attribute.
   * @see #getInterception()
   * @generated
   */
  void setInterception(String value);

  /**
   * Returns the value of the '<em><b>Plus4 Ou Rien</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plus4 Ou Rien</em>' attribute.
   * @see #setPlus4OuRien(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getEnumReglesDeposeCartes_Plus4OuRien()
   * @model
   * @generated
   */
  String getPlus4OuRien();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getPlus4OuRien <em>Plus4 Ou Rien</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plus4 Ou Rien</em>' attribute.
   * @see #getPlus4OuRien()
   * @generated
   */
  void setPlus4OuRien(String value);

} // EnumReglesDeposeCartes
