/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.Model#getUnoRules <em>Uno Rules</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Uno Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.unoDsl.UnoConfig}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uno Rules</em>' containment reference list.
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getModel_UnoRules()
   * @model containment="true"
   * @generated
   */
  EList<UnoConfig> getUnoRules();

} // Model
