/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nombre De Pioches</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.NombreDePioches#getUneFois <em>Une Fois</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.NombreDePioches#getPeutJouer <em>Peut Jouer</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.NombreDePioches#getTroisFois <em>Trois Fois</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getNombreDePioches()
 * @model
 * @generated
 */
public interface NombreDePioches extends EObject
{
  /**
   * Returns the value of the '<em><b>Une Fois</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Une Fois</em>' attribute.
   * @see #setUneFois(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getNombreDePioches_UneFois()
   * @model
   * @generated
   */
  String getUneFois();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.NombreDePioches#getUneFois <em>Une Fois</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Une Fois</em>' attribute.
   * @see #getUneFois()
   * @generated
   */
  void setUneFois(String value);

  /**
   * Returns the value of the '<em><b>Peut Jouer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Peut Jouer</em>' containment reference.
   * @see #setPeutJouer(PeutJouer)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getNombreDePioches_PeutJouer()
   * @model containment="true"
   * @generated
   */
  PeutJouer getPeutJouer();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.NombreDePioches#getPeutJouer <em>Peut Jouer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Peut Jouer</em>' containment reference.
   * @see #getPeutJouer()
   * @generated
   */
  void setPeutJouer(PeutJouer value);

  /**
   * Returns the value of the '<em><b>Trois Fois</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trois Fois</em>' attribute.
   * @see #setTroisFois(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getNombreDePioches_TroisFois()
   * @model
   * @generated
   */
  String getTroisFois();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.NombreDePioches#getTroisFois <em>Trois Fois</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trois Fois</em>' attribute.
   * @see #getTroisFois()
   * @generated
   */
  void setTroisFois(String value);

} // NombreDePioches
