/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Peut Jouer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.PeutJouer#getPeutJouerEnsuite <em>Peut Jouer Ensuite</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.PeutJouer#getPeutPasJouerEnsuite <em>Peut Pas Jouer Ensuite</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getPeutJouer()
 * @model
 * @generated
 */
public interface PeutJouer extends EObject
{
  /**
   * Returns the value of the '<em><b>Peut Jouer Ensuite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Peut Jouer Ensuite</em>' attribute.
   * @see #setPeutJouerEnsuite(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getPeutJouer_PeutJouerEnsuite()
   * @model
   * @generated
   */
  String getPeutJouerEnsuite();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.PeutJouer#getPeutJouerEnsuite <em>Peut Jouer Ensuite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Peut Jouer Ensuite</em>' attribute.
   * @see #getPeutJouerEnsuite()
   * @generated
   */
  void setPeutJouerEnsuite(String value);

  /**
   * Returns the value of the '<em><b>Peut Pas Jouer Ensuite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Peut Pas Jouer Ensuite</em>' attribute.
   * @see #setPeutPasJouerEnsuite(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getPeutJouer_PeutPasJouerEnsuite()
   * @model
   * @generated
   */
  String getPeutPasJouerEnsuite();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.PeutJouer#getPeutPasJouerEnsuite <em>Peut Pas Jouer Ensuite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Peut Pas Jouer Ensuite</em>' attribute.
   * @see #getPeutPasJouerEnsuite()
   * @generated
   */
  void setPeutPasJouerEnsuite(String value);

} // PeutJouer
