/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getNbCartesTalon <em>Nb Cartes Talon</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getTempsLimite <em>Temps Limite</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getDeposeCartes <em>Depose Cartes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getVisibilite <em>Visibilite</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getNombreDePiles <em>Nombre De Piles</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getCartesSpeciales <em>Cartes Speciales</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getNombreDePioches <em>Nombre De Pioches</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getUnoConfig()
 * @model
 * @generated
 */
public interface UnoConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Nb Cartes Talon</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.unoDsl.NbCartesTalon}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb Cartes Talon</em>' attribute.
   * @see org.xtext.example.mydsl.unoDsl.NbCartesTalon
   * @see #setNbCartesTalon(NbCartesTalon)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getUnoConfig_NbCartesTalon()
   * @model
   * @generated
   */
  NbCartesTalon getNbCartesTalon();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getNbCartesTalon <em>Nb Cartes Talon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb Cartes Talon</em>' attribute.
   * @see org.xtext.example.mydsl.unoDsl.NbCartesTalon
   * @see #getNbCartesTalon()
   * @generated
   */
  void setNbCartesTalon(NbCartesTalon value);

  /**
   * Returns the value of the '<em><b>Temps Limite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temps Limite</em>' attribute.
   * @see #setTempsLimite(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getUnoConfig_TempsLimite()
   * @model
   * @generated
   */
  String getTempsLimite();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getTempsLimite <em>Temps Limite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temps Limite</em>' attribute.
   * @see #getTempsLimite()
   * @generated
   */
  void setTempsLimite(String value);

  /**
   * Returns the value of the '<em><b>Depose Cartes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depose Cartes</em>' containment reference.
   * @see #setDeposeCartes(DeposeCartes)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getUnoConfig_DeposeCartes()
   * @model containment="true"
   * @generated
   */
  DeposeCartes getDeposeCartes();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getDeposeCartes <em>Depose Cartes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Depose Cartes</em>' containment reference.
   * @see #getDeposeCartes()
   * @generated
   */
  void setDeposeCartes(DeposeCartes value);

  /**
   * Returns the value of the '<em><b>Visibilite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibilite</em>' containment reference.
   * @see #setVisibilite(Visibilite)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getUnoConfig_Visibilite()
   * @model containment="true"
   * @generated
   */
  Visibilite getVisibilite();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getVisibilite <em>Visibilite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibilite</em>' containment reference.
   * @see #getVisibilite()
   * @generated
   */
  void setVisibilite(Visibilite value);

  /**
   * Returns the value of the '<em><b>Nombre De Piles</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre De Piles</em>' attribute.
   * @see #setNombreDePiles(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getUnoConfig_NombreDePiles()
   * @model
   * @generated
   */
  String getNombreDePiles();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getNombreDePiles <em>Nombre De Piles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre De Piles</em>' attribute.
   * @see #getNombreDePiles()
   * @generated
   */
  void setNombreDePiles(String value);

  /**
   * Returns the value of the '<em><b>Cartes Speciales</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cartes Speciales</em>' containment reference.
   * @see #setCartesSpeciales(CartesSpeciales)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getUnoConfig_CartesSpeciales()
   * @model containment="true"
   * @generated
   */
  CartesSpeciales getCartesSpeciales();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getCartesSpeciales <em>Cartes Speciales</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cartes Speciales</em>' containment reference.
   * @see #getCartesSpeciales()
   * @generated
   */
  void setCartesSpeciales(CartesSpeciales value);

  /**
   * Returns the value of the '<em><b>Nombre De Pioches</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre De Pioches</em>' containment reference.
   * @see #setNombreDePioches(NombreDePioches)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getUnoConfig_NombreDePioches()
   * @model containment="true"
   * @generated
   */
  NombreDePioches getNombreDePioches();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getNombreDePioches <em>Nombre De Pioches</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre De Pioches</em>' containment reference.
   * @see #getNombreDePioches()
   * @generated
   */
  void setNombreDePioches(NombreDePioches value);

} // UnoConfig
