/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.unoDsl.UnoDslFactory
 * @model kind="package"
 * @generated
 */
public interface UnoDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "unoDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/UnoDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "unoDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UnoDslPackage eINSTANCE = org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.unoDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.unoDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Uno Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__UNO_RULES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl <em>Uno Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getUnoConfig()
   * @generated
   */
  int UNO_CONFIG = 1;

  /**
   * The feature id for the '<em><b>Nb Cartes Talon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CONFIG__NB_CARTES_TALON = 0;

  /**
   * The feature id for the '<em><b>Temps Limite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CONFIG__TEMPS_LIMITE = 1;

  /**
   * The feature id for the '<em><b>Depose Cartes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CONFIG__DEPOSE_CARTES = 2;

  /**
   * The feature id for the '<em><b>Visibilite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CONFIG__VISIBILITE = 3;

  /**
   * The feature id for the '<em><b>Nombre De Piles</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CONFIG__NOMBRE_DE_PILES = 4;

  /**
   * The feature id for the '<em><b>Cartes Speciales</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CONFIG__CARTES_SPECIALES = 5;

  /**
   * The feature id for the '<em><b>Nombre De Pioches</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CONFIG__NOMBRE_DE_PIOCHES = 6;

  /**
   * The number of structural features of the '<em>Uno Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CONFIG_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.unoDsl.impl.DeposeCartesImpl <em>Depose Cartes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.unoDsl.impl.DeposeCartesImpl
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getDeposeCartes()
   * @generated
   */
  int DEPOSE_CARTES = 2;

  /**
   * The feature id for the '<em><b>Enum Regles Depose Cartes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPOSE_CARTES__ENUM_REGLES_DEPOSE_CARTES = 0;

  /**
   * The number of structural features of the '<em>Depose Cartes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPOSE_CARTES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.unoDsl.impl.EnumReglesDeposeCartesImpl <em>Enum Regles Depose Cartes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.unoDsl.impl.EnumReglesDeposeCartesImpl
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getEnumReglesDeposeCartes()
   * @generated
   */
  int ENUM_REGLES_DEPOSE_CARTES = 3;

  /**
   * The feature id for the '<em><b>Cumul Plus Deux</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_DEUX = 0;

  /**
   * The feature id for the '<em><b>Cumul Plus Quatre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_QUATRE = 1;

  /**
   * The feature id for the '<em><b>Suite Classique</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_REGLES_DEPOSE_CARTES__SUITE_CLASSIQUE = 2;

  /**
   * The feature id for the '<em><b>Suite Royale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_REGLES_DEPOSE_CARTES__SUITE_ROYALE = 3;

  /**
   * The feature id for the '<em><b>Interception</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_REGLES_DEPOSE_CARTES__INTERCEPTION = 4;

  /**
   * The feature id for the '<em><b>Plus4 Ou Rien</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_REGLES_DEPOSE_CARTES__PLUS4_OU_RIEN = 5;

  /**
   * The number of structural features of the '<em>Enum Regles Depose Cartes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_REGLES_DEPOSE_CARTES_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.unoDsl.impl.VisibiliteImpl <em>Visibilite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.unoDsl.impl.VisibiliteImpl
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getVisibilite()
   * @generated
   */
  int VISIBILITE = 4;

  /**
   * The feature id for the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VISIBILITE__VISIBLE = 0;

  /**
   * The feature id for the '<em><b>Invisible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VISIBILITE__INVISIBLE = 1;

  /**
   * The number of structural features of the '<em>Visibilite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VISIBILITE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.unoDsl.impl.CartesSpecialesImpl <em>Cartes Speciales</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.unoDsl.impl.CartesSpecialesImpl
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getCartesSpeciales()
   * @generated
   */
  int CARTES_SPECIALES = 5;

  /**
   * The feature id for the '<em><b>Enum Cartes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTES_SPECIALES__ENUM_CARTES = 0;

  /**
   * The number of structural features of the '<em>Cartes Speciales</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTES_SPECIALES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.unoDsl.impl.EnumCartesImpl <em>Enum Cartes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.unoDsl.impl.EnumCartesImpl
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getEnumCartes()
   * @generated
   */
  int ENUM_CARTES = 6;

  /**
   * The feature id for the '<em><b>Carte Uno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_CARTES__CARTE_UNO = 0;

  /**
   * The feature id for the '<em><b>Plus Quatre Non Contestable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_CARTES__PLUS_QUATRE_NON_CONTESTABLE = 1;

  /**
   * The feature id for the '<em><b>Carte Zero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_CARTES__CARTE_ZERO = 2;

  /**
   * The feature id for the '<em><b>Carte Sept</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_CARTES__CARTE_SEPT = 3;

  /**
   * The number of structural features of the '<em>Enum Cartes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_CARTES_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.unoDsl.impl.NombreDePiochesImpl <em>Nombre De Pioches</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.unoDsl.impl.NombreDePiochesImpl
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getNombreDePioches()
   * @generated
   */
  int NOMBRE_DE_PIOCHES = 7;

  /**
   * The feature id for the '<em><b>Une Fois</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOMBRE_DE_PIOCHES__UNE_FOIS = 0;

  /**
   * The feature id for the '<em><b>Peut Jouer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOMBRE_DE_PIOCHES__PEUT_JOUER = 1;

  /**
   * The feature id for the '<em><b>Trois Fois</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOMBRE_DE_PIOCHES__TROIS_FOIS = 2;

  /**
   * The number of structural features of the '<em>Nombre De Pioches</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOMBRE_DE_PIOCHES_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.unoDsl.impl.PeutJouerImpl <em>Peut Jouer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.unoDsl.impl.PeutJouerImpl
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getPeutJouer()
   * @generated
   */
  int PEUT_JOUER = 8;

  /**
   * The feature id for the '<em><b>Peut Jouer Ensuite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PEUT_JOUER__PEUT_JOUER_ENSUITE = 0;

  /**
   * The feature id for the '<em><b>Peut Pas Jouer Ensuite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PEUT_JOUER__PEUT_PAS_JOUER_ENSUITE = 1;

  /**
   * The number of structural features of the '<em>Peut Jouer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PEUT_JOUER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.unoDsl.NbCartesTalon <em>Nb Cartes Talon</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.unoDsl.NbCartesTalon
   * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getNbCartesTalon()
   * @generated
   */
  int NB_CARTES_TALON = 9;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.unoDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.unoDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.unoDsl.Model#getUnoRules <em>Uno Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Uno Rules</em>'.
   * @see org.xtext.example.mydsl.unoDsl.Model#getUnoRules()
   * @see #getModel()
   * @generated
   */
  EReference getModel_UnoRules();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.unoDsl.UnoConfig <em>Uno Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uno Config</em>'.
   * @see org.xtext.example.mydsl.unoDsl.UnoConfig
   * @generated
   */
  EClass getUnoConfig();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getNbCartesTalon <em>Nb Cartes Talon</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nb Cartes Talon</em>'.
   * @see org.xtext.example.mydsl.unoDsl.UnoConfig#getNbCartesTalon()
   * @see #getUnoConfig()
   * @generated
   */
  EAttribute getUnoConfig_NbCartesTalon();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getTempsLimite <em>Temps Limite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Temps Limite</em>'.
   * @see org.xtext.example.mydsl.unoDsl.UnoConfig#getTempsLimite()
   * @see #getUnoConfig()
   * @generated
   */
  EAttribute getUnoConfig_TempsLimite();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getDeposeCartes <em>Depose Cartes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Depose Cartes</em>'.
   * @see org.xtext.example.mydsl.unoDsl.UnoConfig#getDeposeCartes()
   * @see #getUnoConfig()
   * @generated
   */
  EReference getUnoConfig_DeposeCartes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getVisibilite <em>Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Visibilite</em>'.
   * @see org.xtext.example.mydsl.unoDsl.UnoConfig#getVisibilite()
   * @see #getUnoConfig()
   * @generated
   */
  EReference getUnoConfig_Visibilite();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getNombreDePiles <em>Nombre De Piles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre De Piles</em>'.
   * @see org.xtext.example.mydsl.unoDsl.UnoConfig#getNombreDePiles()
   * @see #getUnoConfig()
   * @generated
   */
  EAttribute getUnoConfig_NombreDePiles();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getCartesSpeciales <em>Cartes Speciales</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cartes Speciales</em>'.
   * @see org.xtext.example.mydsl.unoDsl.UnoConfig#getCartesSpeciales()
   * @see #getUnoConfig()
   * @generated
   */
  EReference getUnoConfig_CartesSpeciales();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.unoDsl.UnoConfig#getNombreDePioches <em>Nombre De Pioches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nombre De Pioches</em>'.
   * @see org.xtext.example.mydsl.unoDsl.UnoConfig#getNombreDePioches()
   * @see #getUnoConfig()
   * @generated
   */
  EReference getUnoConfig_NombreDePioches();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.unoDsl.DeposeCartes <em>Depose Cartes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Depose Cartes</em>'.
   * @see org.xtext.example.mydsl.unoDsl.DeposeCartes
   * @generated
   */
  EClass getDeposeCartes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.unoDsl.DeposeCartes#getEnumReglesDeposeCartes <em>Enum Regles Depose Cartes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Enum Regles Depose Cartes</em>'.
   * @see org.xtext.example.mydsl.unoDsl.DeposeCartes#getEnumReglesDeposeCartes()
   * @see #getDeposeCartes()
   * @generated
   */
  EReference getDeposeCartes_EnumReglesDeposeCartes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes <em>Enum Regles Depose Cartes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Regles Depose Cartes</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes
   * @generated
   */
  EClass getEnumReglesDeposeCartes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getCumulPlusDeux <em>Cumul Plus Deux</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cumul Plus Deux</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getCumulPlusDeux()
   * @see #getEnumReglesDeposeCartes()
   * @generated
   */
  EAttribute getEnumReglesDeposeCartes_CumulPlusDeux();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getCumulPlusQuatre <em>Cumul Plus Quatre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cumul Plus Quatre</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getCumulPlusQuatre()
   * @see #getEnumReglesDeposeCartes()
   * @generated
   */
  EAttribute getEnumReglesDeposeCartes_CumulPlusQuatre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getSuiteClassique <em>Suite Classique</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Suite Classique</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getSuiteClassique()
   * @see #getEnumReglesDeposeCartes()
   * @generated
   */
  EAttribute getEnumReglesDeposeCartes_SuiteClassique();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getSuiteRoyale <em>Suite Royale</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Suite Royale</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getSuiteRoyale()
   * @see #getEnumReglesDeposeCartes()
   * @generated
   */
  EAttribute getEnumReglesDeposeCartes_SuiteRoyale();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getInterception <em>Interception</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Interception</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getInterception()
   * @see #getEnumReglesDeposeCartes()
   * @generated
   */
  EAttribute getEnumReglesDeposeCartes_Interception();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getPlus4OuRien <em>Plus4 Ou Rien</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Plus4 Ou Rien</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumReglesDeposeCartes#getPlus4OuRien()
   * @see #getEnumReglesDeposeCartes()
   * @generated
   */
  EAttribute getEnumReglesDeposeCartes_Plus4OuRien();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.unoDsl.Visibilite <em>Visibilite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Visibilite</em>'.
   * @see org.xtext.example.mydsl.unoDsl.Visibilite
   * @generated
   */
  EClass getVisibilite();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.Visibilite#getVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visible</em>'.
   * @see org.xtext.example.mydsl.unoDsl.Visibilite#getVisible()
   * @see #getVisibilite()
   * @generated
   */
  EAttribute getVisibilite_Visible();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.Visibilite#getInvisible <em>Invisible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Invisible</em>'.
   * @see org.xtext.example.mydsl.unoDsl.Visibilite#getInvisible()
   * @see #getVisibilite()
   * @generated
   */
  EAttribute getVisibilite_Invisible();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.unoDsl.CartesSpeciales <em>Cartes Speciales</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cartes Speciales</em>'.
   * @see org.xtext.example.mydsl.unoDsl.CartesSpeciales
   * @generated
   */
  EClass getCartesSpeciales();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.unoDsl.CartesSpeciales#getEnumCartes <em>Enum Cartes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Enum Cartes</em>'.
   * @see org.xtext.example.mydsl.unoDsl.CartesSpeciales#getEnumCartes()
   * @see #getCartesSpeciales()
   * @generated
   */
  EReference getCartesSpeciales_EnumCartes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.unoDsl.EnumCartes <em>Enum Cartes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Cartes</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumCartes
   * @generated
   */
  EClass getEnumCartes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteUno <em>Carte Uno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Carte Uno</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteUno()
   * @see #getEnumCartes()
   * @generated
   */
  EAttribute getEnumCartes_CarteUno();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getPlusQuatreNonContestable <em>Plus Quatre Non Contestable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Plus Quatre Non Contestable</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumCartes#getPlusQuatreNonContestable()
   * @see #getEnumCartes()
   * @generated
   */
  EAttribute getEnumCartes_PlusQuatreNonContestable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteZero <em>Carte Zero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Carte Zero</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteZero()
   * @see #getEnumCartes()
   * @generated
   */
  EAttribute getEnumCartes_CarteZero();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteSept <em>Carte Sept</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Carte Sept</em>'.
   * @see org.xtext.example.mydsl.unoDsl.EnumCartes#getCarteSept()
   * @see #getEnumCartes()
   * @generated
   */
  EAttribute getEnumCartes_CarteSept();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.unoDsl.NombreDePioches <em>Nombre De Pioches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nombre De Pioches</em>'.
   * @see org.xtext.example.mydsl.unoDsl.NombreDePioches
   * @generated
   */
  EClass getNombreDePioches();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.NombreDePioches#getUneFois <em>Une Fois</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Une Fois</em>'.
   * @see org.xtext.example.mydsl.unoDsl.NombreDePioches#getUneFois()
   * @see #getNombreDePioches()
   * @generated
   */
  EAttribute getNombreDePioches_UneFois();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.unoDsl.NombreDePioches#getPeutJouer <em>Peut Jouer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Peut Jouer</em>'.
   * @see org.xtext.example.mydsl.unoDsl.NombreDePioches#getPeutJouer()
   * @see #getNombreDePioches()
   * @generated
   */
  EReference getNombreDePioches_PeutJouer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.NombreDePioches#getTroisFois <em>Trois Fois</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Trois Fois</em>'.
   * @see org.xtext.example.mydsl.unoDsl.NombreDePioches#getTroisFois()
   * @see #getNombreDePioches()
   * @generated
   */
  EAttribute getNombreDePioches_TroisFois();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.unoDsl.PeutJouer <em>Peut Jouer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Peut Jouer</em>'.
   * @see org.xtext.example.mydsl.unoDsl.PeutJouer
   * @generated
   */
  EClass getPeutJouer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.PeutJouer#getPeutJouerEnsuite <em>Peut Jouer Ensuite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Peut Jouer Ensuite</em>'.
   * @see org.xtext.example.mydsl.unoDsl.PeutJouer#getPeutJouerEnsuite()
   * @see #getPeutJouer()
   * @generated
   */
  EAttribute getPeutJouer_PeutJouerEnsuite();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.unoDsl.PeutJouer#getPeutPasJouerEnsuite <em>Peut Pas Jouer Ensuite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Peut Pas Jouer Ensuite</em>'.
   * @see org.xtext.example.mydsl.unoDsl.PeutJouer#getPeutPasJouerEnsuite()
   * @see #getPeutJouer()
   * @generated
   */
  EAttribute getPeutJouer_PeutPasJouerEnsuite();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.unoDsl.NbCartesTalon <em>Nb Cartes Talon</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Nb Cartes Talon</em>'.
   * @see org.xtext.example.mydsl.unoDsl.NbCartesTalon
   * @generated
   */
  EEnum getNbCartesTalon();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UnoDslFactory getUnoDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.unoDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.unoDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Uno Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__UNO_RULES = eINSTANCE.getModel_UnoRules();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl <em>Uno Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoConfigImpl
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getUnoConfig()
     * @generated
     */
    EClass UNO_CONFIG = eINSTANCE.getUnoConfig();

    /**
     * The meta object literal for the '<em><b>Nb Cartes Talon</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CONFIG__NB_CARTES_TALON = eINSTANCE.getUnoConfig_NbCartesTalon();

    /**
     * The meta object literal for the '<em><b>Temps Limite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CONFIG__TEMPS_LIMITE = eINSTANCE.getUnoConfig_TempsLimite();

    /**
     * The meta object literal for the '<em><b>Depose Cartes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNO_CONFIG__DEPOSE_CARTES = eINSTANCE.getUnoConfig_DeposeCartes();

    /**
     * The meta object literal for the '<em><b>Visibilite</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNO_CONFIG__VISIBILITE = eINSTANCE.getUnoConfig_Visibilite();

    /**
     * The meta object literal for the '<em><b>Nombre De Piles</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CONFIG__NOMBRE_DE_PILES = eINSTANCE.getUnoConfig_NombreDePiles();

    /**
     * The meta object literal for the '<em><b>Cartes Speciales</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNO_CONFIG__CARTES_SPECIALES = eINSTANCE.getUnoConfig_CartesSpeciales();

    /**
     * The meta object literal for the '<em><b>Nombre De Pioches</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNO_CONFIG__NOMBRE_DE_PIOCHES = eINSTANCE.getUnoConfig_NombreDePioches();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.unoDsl.impl.DeposeCartesImpl <em>Depose Cartes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.unoDsl.impl.DeposeCartesImpl
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getDeposeCartes()
     * @generated
     */
    EClass DEPOSE_CARTES = eINSTANCE.getDeposeCartes();

    /**
     * The meta object literal for the '<em><b>Enum Regles Depose Cartes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPOSE_CARTES__ENUM_REGLES_DEPOSE_CARTES = eINSTANCE.getDeposeCartes_EnumReglesDeposeCartes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.unoDsl.impl.EnumReglesDeposeCartesImpl <em>Enum Regles Depose Cartes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.unoDsl.impl.EnumReglesDeposeCartesImpl
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getEnumReglesDeposeCartes()
     * @generated
     */
    EClass ENUM_REGLES_DEPOSE_CARTES = eINSTANCE.getEnumReglesDeposeCartes();

    /**
     * The meta object literal for the '<em><b>Cumul Plus Deux</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_DEUX = eINSTANCE.getEnumReglesDeposeCartes_CumulPlusDeux();

    /**
     * The meta object literal for the '<em><b>Cumul Plus Quatre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_REGLES_DEPOSE_CARTES__CUMUL_PLUS_QUATRE = eINSTANCE.getEnumReglesDeposeCartes_CumulPlusQuatre();

    /**
     * The meta object literal for the '<em><b>Suite Classique</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_REGLES_DEPOSE_CARTES__SUITE_CLASSIQUE = eINSTANCE.getEnumReglesDeposeCartes_SuiteClassique();

    /**
     * The meta object literal for the '<em><b>Suite Royale</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_REGLES_DEPOSE_CARTES__SUITE_ROYALE = eINSTANCE.getEnumReglesDeposeCartes_SuiteRoyale();

    /**
     * The meta object literal for the '<em><b>Interception</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_REGLES_DEPOSE_CARTES__INTERCEPTION = eINSTANCE.getEnumReglesDeposeCartes_Interception();

    /**
     * The meta object literal for the '<em><b>Plus4 Ou Rien</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_REGLES_DEPOSE_CARTES__PLUS4_OU_RIEN = eINSTANCE.getEnumReglesDeposeCartes_Plus4OuRien();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.unoDsl.impl.VisibiliteImpl <em>Visibilite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.unoDsl.impl.VisibiliteImpl
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getVisibilite()
     * @generated
     */
    EClass VISIBILITE = eINSTANCE.getVisibilite();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VISIBILITE__VISIBLE = eINSTANCE.getVisibilite_Visible();

    /**
     * The meta object literal for the '<em><b>Invisible</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VISIBILITE__INVISIBLE = eINSTANCE.getVisibilite_Invisible();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.unoDsl.impl.CartesSpecialesImpl <em>Cartes Speciales</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.unoDsl.impl.CartesSpecialesImpl
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getCartesSpeciales()
     * @generated
     */
    EClass CARTES_SPECIALES = eINSTANCE.getCartesSpeciales();

    /**
     * The meta object literal for the '<em><b>Enum Cartes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARTES_SPECIALES__ENUM_CARTES = eINSTANCE.getCartesSpeciales_EnumCartes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.unoDsl.impl.EnumCartesImpl <em>Enum Cartes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.unoDsl.impl.EnumCartesImpl
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getEnumCartes()
     * @generated
     */
    EClass ENUM_CARTES = eINSTANCE.getEnumCartes();

    /**
     * The meta object literal for the '<em><b>Carte Uno</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_CARTES__CARTE_UNO = eINSTANCE.getEnumCartes_CarteUno();

    /**
     * The meta object literal for the '<em><b>Plus Quatre Non Contestable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_CARTES__PLUS_QUATRE_NON_CONTESTABLE = eINSTANCE.getEnumCartes_PlusQuatreNonContestable();

    /**
     * The meta object literal for the '<em><b>Carte Zero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_CARTES__CARTE_ZERO = eINSTANCE.getEnumCartes_CarteZero();

    /**
     * The meta object literal for the '<em><b>Carte Sept</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_CARTES__CARTE_SEPT = eINSTANCE.getEnumCartes_CarteSept();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.unoDsl.impl.NombreDePiochesImpl <em>Nombre De Pioches</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.unoDsl.impl.NombreDePiochesImpl
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getNombreDePioches()
     * @generated
     */
    EClass NOMBRE_DE_PIOCHES = eINSTANCE.getNombreDePioches();

    /**
     * The meta object literal for the '<em><b>Une Fois</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOMBRE_DE_PIOCHES__UNE_FOIS = eINSTANCE.getNombreDePioches_UneFois();

    /**
     * The meta object literal for the '<em><b>Peut Jouer</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOMBRE_DE_PIOCHES__PEUT_JOUER = eINSTANCE.getNombreDePioches_PeutJouer();

    /**
     * The meta object literal for the '<em><b>Trois Fois</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOMBRE_DE_PIOCHES__TROIS_FOIS = eINSTANCE.getNombreDePioches_TroisFois();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.unoDsl.impl.PeutJouerImpl <em>Peut Jouer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.unoDsl.impl.PeutJouerImpl
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getPeutJouer()
     * @generated
     */
    EClass PEUT_JOUER = eINSTANCE.getPeutJouer();

    /**
     * The meta object literal for the '<em><b>Peut Jouer Ensuite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PEUT_JOUER__PEUT_JOUER_ENSUITE = eINSTANCE.getPeutJouer_PeutJouerEnsuite();

    /**
     * The meta object literal for the '<em><b>Peut Pas Jouer Ensuite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PEUT_JOUER__PEUT_PAS_JOUER_ENSUITE = eINSTANCE.getPeutJouer_PeutPasJouerEnsuite();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.unoDsl.NbCartesTalon <em>Nb Cartes Talon</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.unoDsl.NbCartesTalon
     * @see org.xtext.example.mydsl.unoDsl.impl.UnoDslPackageImpl#getNbCartesTalon()
     * @generated
     */
    EEnum NB_CARTES_TALON = eINSTANCE.getNbCartesTalon();

  }

} //UnoDslPackage
