/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Visibilite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.Visibilite#getVisible <em>Visible</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.unoDsl.Visibilite#getInvisible <em>Invisible</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getVisibilite()
 * @model
 * @generated
 */
public interface Visibilite extends EObject
{
  /**
   * Returns the value of the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible</em>' attribute.
   * @see #setVisible(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getVisibilite_Visible()
   * @model
   * @generated
   */
  String getVisible();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.Visibilite#getVisible <em>Visible</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible</em>' attribute.
   * @see #getVisible()
   * @generated
   */
  void setVisible(String value);

  /**
   * Returns the value of the '<em><b>Invisible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invisible</em>' attribute.
   * @see #setInvisible(String)
   * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage#getVisibilite_Invisible()
   * @model
   * @generated
   */
  String getInvisible();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.unoDsl.Visibilite#getInvisible <em>Invisible</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Invisible</em>' attribute.
   * @see #getInvisible()
   * @generated
   */
  void setInvisible(String value);

} // Visibilite
