/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.unoDsl.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.example.mydsl.unoDsl.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.unoDsl.UnoDslPackage
 * @generated
 */
public class UnoDslSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static UnoDslPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UnoDslSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = UnoDslPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case UnoDslPackage.MODEL:
      {
        Model model = (Model)theEObject;
        T result = caseModel(model);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case UnoDslPackage.UNO_CONFIG:
      {
        UnoConfig unoConfig = (UnoConfig)theEObject;
        T result = caseUnoConfig(unoConfig);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case UnoDslPackage.DEPOSE_CARTES:
      {
        DeposeCartes deposeCartes = (DeposeCartes)theEObject;
        T result = caseDeposeCartes(deposeCartes);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case UnoDslPackage.ENUM_REGLES_DEPOSE_CARTES:
      {
        EnumReglesDeposeCartes enumReglesDeposeCartes = (EnumReglesDeposeCartes)theEObject;
        T result = caseEnumReglesDeposeCartes(enumReglesDeposeCartes);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case UnoDslPackage.VISIBILITE:
      {
        Visibilite visibilite = (Visibilite)theEObject;
        T result = caseVisibilite(visibilite);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case UnoDslPackage.CARTES_SPECIALES:
      {
        CartesSpeciales cartesSpeciales = (CartesSpeciales)theEObject;
        T result = caseCartesSpeciales(cartesSpeciales);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case UnoDslPackage.ENUM_CARTES:
      {
        EnumCartes enumCartes = (EnumCartes)theEObject;
        T result = caseEnumCartes(enumCartes);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case UnoDslPackage.NOMBRE_DE_PIOCHES:
      {
        NombreDePioches nombreDePioches = (NombreDePioches)theEObject;
        T result = caseNombreDePioches(nombreDePioches);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case UnoDslPackage.PEUT_JOUER:
      {
        PeutJouer peutJouer = (PeutJouer)theEObject;
        T result = casePeutJouer(peutJouer);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Model</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseModel(Model object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Uno Config</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Uno Config</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseUnoConfig(UnoConfig object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Depose Cartes</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Depose Cartes</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDeposeCartes(DeposeCartes object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Enum Regles Depose Cartes</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Enum Regles Depose Cartes</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEnumReglesDeposeCartes(EnumReglesDeposeCartes object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Visibilite</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Visibilite</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseVisibilite(Visibilite object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Cartes Speciales</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Cartes Speciales</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCartesSpeciales(CartesSpeciales object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Enum Cartes</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Enum Cartes</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEnumCartes(EnumCartes object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Nombre De Pioches</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Nombre De Pioches</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNombreDePioches(NombreDePioches object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Peut Jouer</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Peut Jouer</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePeutJouer(PeutJouer object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //UnoDslSwitch
